excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://dixondonald.github.io
title: Donald Dixon
email: dixondonald@gmail.com
author: Donald Dixon
description: My personal portfolio
paginate: 5
google_analytics: 